export const API = {
  eventDetails: "",
  casino: "",
  auth: "",
  order: "",
  pnl: "",
  bets: "",
  history: "",
  payout: "",
  rules: "",
};

export const Settings = {
  otp: "",
  casino: "",
  siteTitle: "",
  forceLogin: "",
  registration: "",
  demoLogin: "",
  withdraw: "",
  deposit: "",
  siteUrl: "",
  balanceApiLoop: "",
  disabledDevtool: "",
  casinoCurrency: "",
  interval: "",
  logoFormat: "",
  logoHeight: "",
  logoWidth: "",
  apkLink: "",
  betFairCashOut: "",
  registrationWhatsapp: "",
  build: "",
  mac88: "",
  aura: "",
  referral: "",
  b2c: "",
};
